---
# This role is experimental and still a work in progress...
# TODO: Initial attempt will fail, currently requires a "cloudflared tunnel login" which prompts the user to visit the site
# Currently this role assumes you've already performed the cloudflared login steps.
- name: check for cloudflared
  stat:
    path: /usr/local/bin/cloudflared
  register: cloudflared_binary

- name: install golang packages
  apt:
    name:
      - 'golang-go'
      - 'make'
    state: present
    update_cache: true
  register: apt_install_cloudflared_deps
  retries: 5
  until: apt_install_cloudflared_deps is success
  when: not cloudflared_binary.stat.exists

- name: create temp folder
  tempfile:
    state: directory
    suffix: cloudflared
  register: tempfolder
  become: false
  when: not cloudflared_binary.stat.exists

- name: clone cloudflared repository locally
  git:
    repo: https://github.com/cloudflare/cloudflared.git
    dest: "{{ tempfolder.path }}"
    version: '{{ cloudflared_version }}'
  when: not cloudflared_binary.stat.exists

- name: compile cloudflared binary
  make:
    chdir: "{{ tempfolder.path }}"
    target: cloudflared
  when: not cloudflared_binary.stat.exists

- name: copy cloudflared binary to /usr/local/bin
  copy:
    src: "{{ tempfolder.path }}/cloudflared"
    remote_src: true
    dest: /usr/local/bin/cloudflared
    mode: '0755'
  when: not cloudflared_binary.stat.exists
