---
# Role - common
common_packages:
  - rxvt-unicode-terminfo
  - fakeroot
  - binutils
  - make
  - gcc
  - bash-completion
  - inetutils
  - bind-tools
  - ca-certificates
  - zip
  - jq
  - git
  - vim
  - curl
  - net-tools
  - ipvsadm
  - sysstat
  - python-pyopenssl # Needed for ansible 'openssl_certificate_info' module
  - ethtool
  - ebtables
common_rpi_cmd_file: /boot/cmdline.txt
common_rpi_config_file: /boot/config.txt
