---
# Role - common
common_packages:
  - apt-transport-https
  - software-properties-common
  - ca-certificates
  - zip
  - jq
  - git
  - vim
  - curl
  - ipvsadm
  - net-tools
  - python3-openssl # Needed for ansible 'openssl_certificate_info' module
  - python3-pip
