---
# Role: common
common_packages:
  - apt-transport-https
  - software-properties-common
  - ca-certificates
  - zip
  - jq
  - git
  - vim
  - curl
  - net-tools
  - python-pyopenssl # Needed for ansible 'openssl_certificate_info' module
