---
- name: Converge
  hosts: all
  tasks:
  - name: 'ensure necessary packages are installed'
    apt:
      name: '{{ item }}'
      update_cache: yes
    loop:
    - gpg-agent
    - bash-completion
  - name: 'Include cri'
    include_role:
      name: 'cri'
