---
####
# Role - common
####
# common_upgrade_packages: true
# common_reboot_handler_enabled: true
# common_timezone: UTC
# common_usb_ssd_enabled: false
# common_usb_ssd_device_id: ""
# common_rpi_overclock: false
# common_rpi_poe_hat: false
# common_log2ram_enabled: false
# common_log2ram_version: v1.4
# common_log2ram_size: 128M

####
# Role - kubernetes
####
kubernetes_kubectl_version: 1.21.0-00
kubernetes_kubelet_version: 1.21.0-00
kubernetes_kubeadm_version: 1.21.0-00

####
# Role - keepalived
####
# keepalived_vip: ''
# keepalived_interface: "{{ ansible_default_ipv4['interface'] }}"

####
# Role - cri
####
cri_plugin: containerd
# cri_containerd_version: '1.4.3'

####
# Role - cni
####
# cni_plugin: 'calico'
# cni_bgp_peer_address: 192.168.0.1
# cni_bgp_peer_asn: 64512
# cni_cilium_helm_version: 1.9.3
# cni_cilium_image_version: v1.9.3
# cni_cilium_hubble_enabled: false
# cni_cilium_enovy_proxy_image_version: v1.16.2
# cni_cilium_bpf_hostrouting: "true"
# cni_cilium_bpf_tproxy: "false"
# cni_cilium_bpf_masquerade: "true"
# cni_cilium_endpoint_routes: "false"

####
# Role: Storage
####
# storage_enabled: true

####
# Role: docker_cache
####
# docker_cache_enable: false

####
# Role - cloudflared
####
# Cloudflare options for exposing Kubernetes services via HTTPS/SSH
# cloudflared_enabled: false
# cloudflared_kube_api_server_dns: ''
# cloudflared_version: 2021.2.5
