---
# Configure user Ansible uses to ssh into the machine
# Note: Should match the user configured via cloud-init
ansible_user: pi

# Configure Log2ram version and memory allocation
log2ram_version: v1.4
log2ram_size: 128M

# Configure Kubernetes package versions independently - see docs for guidance
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl
# Note: To check available versions for a package "apt list -a <package-name>""
kubectl_version: 1.18.2-00
kubelet_version: 1.18.2-00
kubeadm_version: 1.18.2-00

# Cloudflare options for exposing Kubernetes services via HTTPS/SSH
cloudflared_kube_api_server_dns: 'api-server.raspbernetes.com'
cloudflared_ingress_sans: '*.raspbernetes.com'
cloudflared_ssh_port: 22

# Configure Kubernetes container network interface (CNI)
# Options: "weave" or "flannel"
# Default: "weave"
cni: weave

# Configure Kubernetes container runtime (CRI)
# Options: "containerd" or "docker"
# Default: "containerd"
cri: containerd

# Role: common
#common_rpi_overclock: true
#common_rpi_poe_hat: true
