---
# Role: common
#common_upgrade_packages: true
#common_reboot_handler_enabled: true
#common_timezone: UTC
#common_rpi_overclock: false
#common_rpi_poe_hat: false
#common_log2ram_version: v1.4
#common_log2ram_size: 128M

# Role: keepalived
#keepalived_vip: ''

# Role: kubernetes
#kubernetes_kubectl_version: 1.18.2-00
#kubernetes_kubelet_version: 1.18.2-00
#kubernetes_kubeadm_version: 1.18.2-00

# Role: cri
#cri_plugin: docker

# Role: openebs
#openebs_enabled: true
