---
# https://github.com/openebs/cstor-operators/blob/master/docs/quick.md#prerequisites
- name: install openebs required packages
  apt:
    name: open-iscsi
    install_recommends: false
    update_cache: true
    force_apt_get: true
  register: apt_install_iscsi
  retries: 5
  until: apt_install_iscsi is success
  notify: restart iscsid

- name: copy iscsi_tcp config file
  copy:
    src: openebs/iscsi_tcp.conf
    dest: '/etc/modules-load.d/openebs-iscsi_tcp.conf'
    owner: root
    group: root
    mode: '0644'

- name: load iscsi_tcp
  modprobe:
    name: iscsi_tcp
    state: present
