---
cri_plugin: 'containerd'

# Defaults for ContainerD
cri_containerd_package: 'containerd.io'
cri_containerd_version: '1.3.9'

# ContainerD default directories
cri_containerd_config_dir: '/etc/containerd'
cri_containerd_metadata_dir: '/var/lib/containerd'
cri_containerd_state_dir: '/run/containerd'

# docker-ce apt repo
cri_containerd_repo_base_url: 'https://download.docker.com/linux/{{ ansible_distribution|lower }}'
cri_containerd_repo_gpgkey: '{{ cri_containerd_repo_base_url }}/gpg'

# Defaults for crictl
cri_crictl_version: 'v1.20.0'
cri_crictl_download_url: 'https://github.com/kubernetes-sigs/cri-tools/releases/download/{{ cri_crictl_version }}/crictl-{{ cri_crictl_version }}-linux-{{ cri_architecture }}.tar.gz'

docker_cache_enable: false
