---
- name: 'install containerd on debian based platforms'
  block:
  - name: 'containerd | ensure docker.io apt repository public key is installed'
    ansible.builtin.apt_key:
      url: '{{ cri_containerd_repo_gpgkey }}'
  - name: 'containerd | ensure docker.io apt repository is enabled'
    ansible.builtin.apt_repository:
      repo: 'deb {{ cri_containerd_repo_base_url }} {{ ansible_distribution_release }} stable'
      state: 'present'
  # this is to prevent apt upgrade from breaking kubernetes
  - name: 'containerd | pin package version to prevent os upgrade clubbing'
    ansible.builtin.template:
      src: 'apt-preferences.d/containerd.j2'
      dest: '/etc/apt/preferences.d/containerd'
      owner: 'root'
      mode: 0644
  - name: 'containerd | install package from apt repository'
    ansible.builtin.apt:
      name:
      - '{{ cri_containerd_package_name[cri_containerd_version | string] }}'
      state: 'present'
      update_cache: true
      cache_valid_time: 3600
  when: ansible_os_family|lower == 'debian'

# Archlinux installation of containerd package
- name: 'containerd | install containerd package'
  pacman:
    name: 'containerd'
    state: 'present'
    update_cache: true
  when: ansible_os_family | lower == 'archlinux'

- name: 'containerd | ensure config directory exists and has proper ownerships'
  ansible.builtin.file:
    path: '{{ cri_containerd_config_dir }}'
    state: 'directory'
    mode: 0755
    owner: 'root'
    group: 'root'

- name: 'containerd | generate default configuration file'
  ansible.builtin.command: |
    containerd config default
  register: containerd_default_config_file
  changed_when: false
  when: cri_containerd_default_config

- name: 'containerd | ensure default configuration'
  ansible.builtin.copy:
    dest: '{{ cri_containerd_config_dir }}/config.toml'
    content: '{{ containerd_default_config_file.stdout }}'
  notify: restart cri
  when: cri_containerd_default_config
