---
- name: Register master join command
  changed_when: false
  local_action: command cat output/k8s-master-join-command
  register: k8s_master_join
  vars:
    ansible_become: no

- name: Execute master kubeadm join
  command: '{{ k8s_master_join.stdout }}'
  args:
    creates: /etc/kubernetes/kubelet.conf
