---
cri_supported_os_families:
- debian
- archlinux

cri_supported_plugins:
- docker
- containerd

containerd_package_name:
  'latest': '{{ containerd_package }}'
  '1.3.7': '{{ containerd_package }}=1.3.7-1'
  '1.3.9': '{{ containerd_package }}=1.3.9-1'
  '1.4.3': '{{ containerd_package }}=1.4.3-1'
  'stable': '{{ containerd_package }}=1.3.9-1'

cri_architecture_map:
  amd64: 'amd64'
  x86_64: 'amd64'
  arm6l: 'arm'
  arm7l: 'arm'
  aarch64: 'arm64'
  32-bit: '386'
  64-bit: 'amd64'
cri_architecture: '{{ cri_architecture_map[ansible_architecture] }}'

cri_socket_map:
  crio: 'unix:///var/run/crio/crio.sock'
  containerd: 'unix:///run/containerd/containerd.sock'
  docker: 'unix:///var/run/dockershim.sock'
cri_socket_path: '{{ cri_socket_map[cri_plugin] }}'
