# Instructions: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker
---
- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repository for stable version
  apt_repository:
    repo: deb [arch=arm64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename}} stable
    state: present

- name: Install docker and its dependencies
  apt:
    name: '{{ packages }}'
    state: present
    update_cache: yes
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Copy Docker Daemon Config
  copy:
    src: '{{ item }}'
    dest: '/etc/docker/daemon.json'
    owner: root
    group: root
    mode: 0644
  with_items:
    - daemon.json

- name: Create a Docker service
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0755'

- name: Reload service daemon-reload
  systemd:
    name: daemon-reload
    daemon_reload: yes

- name: Restart service Docker
  systemd:
    name: docker
    state: restarted
