---
ansible_user: pi

log2ram_version: v1.4
log2ram_size: 128M

# Configure Kubernetes binary versions
kubernetes_version: 1.9.6
kubelet_version: 1.9.6-0
kubeadm_version: 1.10.1

load_balancer_dns: 192.168.1.100
load_balancer_port: 8443

# Configure Kubernetes CNI
# Options: "weave" or "flannel"
# Default: "weave"
cni: weave

# Configure Kubernetes CRI
# Options: "containerd" or "docker"
# Default: "containerd" for now
cri: containerd


# Network interface
# Options: "eth0" or "wlan0"
# Default: "eth0"
network_interface: eth0
