---
# Configure user Ansible uses to ssh into the machine
# Note: Should match the user configured via cloud-init
ansible_user: pi

# Configure Log2ram version and memory allocation
log2ram_version: v1.4
log2ram_size: 128M

# Configure Kubernetes package versions independently - see docs for guidance
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl
# Note: To check available versions for a package "apt list -a <package-name>""
kubectl_version: 1.18.2-00
kubelet_version: 1.18.2-00
kubeadm_version: 1.18.2-00

# Cloudflare options for exposing Kubernetes services via HTTPS/SSH
kube_api_server_dns: 'raspbernetes.com'
ingress_sans: '*.raspbernetes.com'
ssh_port: 22

# Nginx Ingress IP and port
nginx_ingress_dns: 192.168.1.155
nginx_port: 80

# Virtual IP and port used by Keepalived
load_balancer_dns: 192.168.1.200
load_balancer_port: 6443

# Configure Kubernetes container network interface (CNI)
# Options: "weave" or "flannel"
# Default: "weave"
cni: weave

# Configure Kubernetes container runtime (CRI)
# Options: "containerd" or "docker"
# Default: "containerd"
cri: containerd

# Network interface
# Note: Flash SD with wlan0 configuration doesn't guarantee IP allocation is static and match as defined in eth0
# Options: "eth0" or "wlan0"
# Default: "eth0"
network_interface: eth0
