---
- name: Register worker join command
  changed_when: false
  local_action: command cat output/k8s-worker-join-command
  register: k8s_worker_join
  run_once: yes
  vars:
    ansible_become: no

- name: Execute worker kubeadm join
  command: '{{ k8s_worker_join.stdout }}'
  args:
    creates: /etc/kubernetes/kubelet.conf
